# Generated by Django 4.2.21 on 2025-05-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, default='project_images/default.png', null=True, upload_to='project_images/'),
        ),
    ]
