# Generated by Django 4.2.21 on 2025-05-19 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pages.projects'),
            preserve_default=False,
        ),
    ]
