# Generated by Django 5.1.7 on 2025-05-20 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_stocks_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('possibility', models.FloatField(help_text='Value between 0 and 1')),
                ('effect', models.CharField(help_text="Effect like '*2', '+5', '-3' etc.", max_length=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pages.stocks')),
            ],
        ),
    ]
