# Generated by Django 5.1.7 on 2025-05-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='possibility',
            field=models.CharField(help_text="Ex: 0.5 or stock('X') * 0.3", max_length=100),
        ),
    ]
