# Generated by Django 5.1.7 on 2025-05-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_events_possibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='initial_value',
            field=models.FloatField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
