# Generated by Django 5.1.7 on 2025-05-22 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_stocks_initial_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_expression', models.CharField(help_text='Ex: \'*2\', \'+ stock("Y")\', \'-3\'', max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='pages.events')),
                ('target_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.stocks')),
            ],
        ),
    ]
