# Generated by Django 5.1.7 on 2025-05-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_effects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='effect',
        ),
    ]
